R: put compilers and flags into configure.in.

diff --git a/interfaces/R/configure.in.in b/interfaces/R/configure.in.in
--- a/interfaces/R/configure.in.in
+++ b/interfaces/R/configure.in.in
@@ -2,8 +2,24 @@ AC_INIT(igraph, @VERSION@, csardi@rmki.kfki.hu)
 AC_CONFIG_SRCDIR(src/rinterface.c)
 AC_CONFIG_HEADERS(src/config.h)
 
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+   echo "could not determine R_HOME"
+   exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CXX=`"${R_HOME}/bin/R" CMD config CXX`
+FC=`"${R_HOME}/bin/R" CMD config FC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CXXFLAGS=`"${R_HOME}/bin/R" CMD config CXXFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+FCFLAGS=`"${R_HOME}/bin/R" CMD config FCFLAGS`
+FLIBS=`"${R_HOME}/bin/R" CMD config FLIBS`
+
 AC_LANG(C)
 AC_PROG_CC
+
+AC_PROG_FC
 
 # Tricky check for C++ compiler, because Autoconf has a weird bug:
 # http://lists.gnu.org/archive/html/autoconf/2006-03/msg00067.html
